services:
  jekyll:
    build: .
    container_name: al-folio-website
    user: root
    working_dir: /srv/jekyll
    command: bash -c "
      bundle config set --local path 'vendor/bundle'
      && bundle install
      && bundle exec jekyll serve --watch --port=8080 --host=0.0.0.0 --livereload --verbose --trace"
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll